data mutualfunds;
	infile "/folders/myshortcuts/ST2137/Project/mutual-fund-analysis/mutual funds.csv" delimiter=',' firstobs=2 dsd;
	length Fund $50;
	length Type $12;
	length Turnover $12;
	length Risk $12;
	input Fund $ Type $ Assets Fees $ Expense_ratio Return_2001 Three_Year_Return Five_Year_Return Turnover $ Risk $ Best_Quarter Worst_Quarter;
proc means data=mutualfunds;
	title "Descriptive Statistics for 2001 Returns";
	var Return_2001;
proc means data=mutualfunds;
	title "Descriptive Statistics for Three Year Returns";
	var Three_Year_Return;
proc means data=mutualfunds;
	title "Descriptive Statistics for Five Year Returns";
	var Five_Year_Return;
	
proc freq data=mutualfunds;
	Title "Frequency Counts for Mutual Fund Variables";
	tables Type Risk Fees;
	
proc glm data=mutualfunds;
	title "Analysis of Fees to 2001 Return";
	class Fees;
	model Return_2001 = Fees;
	means Fees;
proc glm data=mutualfunds;
	title "Analysis of Fees to Three Year Return";
	class Fees;
	model Three_Year_Return = Fees;
	means Fees;
proc glm data=mutualfunds;
	title "Analysis of Fees to Five Year Return";
	class Fees;
	model Five_Year_Return = Fees;
	means Fees;
proc glm data=mutualfunds;
	title "Analysis of Risk to 2001 Return";
	class Risk;
	model Return_2001 = Risk;
proc glm data=mutualfunds;
	title "Analysis of Risk to Three Year Return";
	class Risk;
	model Three_Year_Return = Risk;
proc glm data=mutualfunds;
	title "Analysis of Risk to Five Year Return";
	class Risk;
	model Five_Year_Return = Risk;
run;

